#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER --dbname $POSTGRES_DB <<-EOSQL
  CREATE USER $SED_PERSISTENCE_CONNECTOR_USER WITH ENCRYPTED PASSWORD '$SED_PERSISTENCE_CONNECTOR_PASSWORD';
  CREATE DATABASE $SED_PERSISTENCE_CONNECTOR_DATABASE;
  GRANT ALL PRIVILEGES ON DATABASE $SED_PERSISTENCE_CONNECTOR_DATABASE TO $SED_PERSISTENCE_CONNECTOR_USER;
  \c $SED_PERSISTENCE_CONNECTOR_DATABASE
  GRANT USAGE, CREATE ON SCHEMA public TO $SED_PERSISTENCE_CONNECTOR_USER
EOSQL
