name: participant

services:

  participant-dlt-booth:
    image: ghcr.io/sedimark/dlt-booth:latest
    restart: unless-stopped
    depends_on:
      participant-postgres:
        condition: service_healthy
    ports:
      - "${SED_DLT_BOOTH_EXTERNAL_PORT:-8085}:8085"
    env_file:
#      - ./assets/env/participant_persistence.env # Not needed, injected by docker-compose.yml
      - ./assets/env/participant_dltbooth.env
      - ./assets/env/sed_baseline_infrastructure.env
    environment:
      DB_HOST: participant-postgres
      DB_PORT: 5432
      DB_NAME: ${SED_PERSISTENCE_DLTBOOTH_DATABASE}
      DB_USER: ${SED_PERSISTENCE_DLTBOOTH_USER}
      DB_PASSWORD: ${SED_PERSISTENCE_DLTBOOTH_PASSWORD}
      DB_MAX_POOL_SIZE: 16
    volumes:
      - "./assets/participant/dlt-booth:/data"
    logging:
      driver: local
    networks:
      participant_network:
        ipv4_address: "${SUBNET_PREFIX:-172.23.0}.20"
    profiles:
      - onboarding
      - marketplace


  participant-connector-controlplane:
    image: ghcr.io/sedimark/sed-conn-controlplane:0.1
    pull_policy: never
    depends_on:
      participant-postgres:
        condition: service_healthy
    ports:
      - "${SED_CONN_CP_EXTERNAL_MANAGEMENT_PORT:-8181}:8181"
      - "${SED_CONN_CP_EXTERNAL_CONTROL_PORT:-9191}:9191"
      - "${SED_CONN_CP_EXTERNAL_VERSION_PORT:-7171}:7171"
      - "${SED_CONN_CP_EXTERNAL_DSP_PORT:-8282}:8282"
    env_file:
#      - ./assets/env/participant_persistence.env # Not needed, injected by docker-compose.yml
      - ./assets/env/participant_connector.env
    environment:
      EDC_DATASOURCE_DEFAULT_URL: jdbc:postgresql://participant-postgres:5432/${SED_PERSISTENCE_CONNECTOR_DATABASE}
      EDC_DATASOURCE_DEFAULT_USER: ${SED_PERSISTENCE_CONNECTOR_USER}
      EDC_DATASOURCE_DEFAULT_PASSWORD: ${SED_PERSISTENCE_CONNECTOR_PASSWORD}
      EDC_SQL_SCHEMA_AUTOCREATE: true
      LOG_LEVEL: debug
    healthcheck:
      test: ["CMD", "curl", "--fail http://localhost:$$WEB_HTTP_PORT$$WEB_HTTP_PATH}/check/health"]
      start_period: 30s
      timeout: 5s
      interval: 5s
      retries: 10
    logging:
      driver: local
    networks:
      participant_network:
        ipv4_address: "${SUBNET_PREFIX:-172.23.0}.10"
    profiles:
      - operation
      - marketplace


  participant-connector-dataplane:
    image: ghcr.io/sedimark/sed-conn-dataplane:0.1
    pull_policy: never
    depends_on:
      participant-postgres:
        condition: service_healthy
    ports:
      - "${SED_CONN_DP_EXTERNAL_API_PORT:-8185}:8185"
    env_file:
#      - ./assets/env/participant_persistence.env # Not needed, injected by docker-compose.yml
      - ./assets/env/participant_connector.env
    environment:
      EDC_DATASOURCE_DEFAULT_URL: jdbc:postgresql://participant-postgres:5432/${SED_PERSISTENCE_CONNECTOR_DATABASE}
      EDC_DATASOURCE_DEFAULT_USER: ${SED_PERSISTENCE_CONNECTOR_USER}
      EDC_DATASOURCE_DEFAULT_PASSWORD: ${SED_PERSISTENCE_CONNECTOR_PASSWORD}
      EDC_SQL_SCHEMA_AUTOCREATE: true
#      LOG_LEVEL: debug
    healthcheck:
      test: ["CMD", "curl", "--fail http://localhost:$$WEB_HTTP_PORT$$WEB_HTTP_PATH/check/health"]
      start_period: 30s
      timeout: 5s
      interval: 5s
      retries: 10
    logging:
      driver: local
    networks:
      participant_network:
        ipv4_address: "${SUBNET_PREFIX:-172.23.0}.11"
    profiles:
      - operation
      - marketplace


  participant-verifier:
    image: ghcr.io/cybersecurity-links/mediterraneus-verifier:0.0.2
    restart: unless-stopped
    ports:
      - "1235"
    env_file:
      - ./assets/env/participant_verifier.env
      - ./assets/env/sed_baseline_infrastructure.env
    logging:
      driver: local
    networks:
      participant_network:
        ipv4_address: "${SUBNET_PREFIX:-172.23.0}.40"
    profiles:
      - operation
      - marketplace


  participant-postgres:
    image: postgres:alpine
    env_file:
      - assets/env/base_interpolation.env
    environment:
      POSTGRES_DB: ${SED_PERSISTENCE_POSTGRES_DB:-postgres}
      POSTGRES_USER: ${SED_PERSISTENCE_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${SED_PERSISTENCE_POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
      POSTGRES_LOGGING_COLLECTOR: 'on'
      POSTGRES_LOG_MIN_MESSAGES: 'DEBUG1'
    volumes:
      - participant-postgres-vol:/data/postgres
      - ./assets/initdb:/docker-entrypoint-initdb.d/:ro
    ports:
      - "${SED_POSTGRES_EXTERNAL_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      start_period: 30s
      timeout: 10s
      interval: 10s
      retries: 5
    logging:
      driver: local
    networks:
      participant_network:
        ipv4_address: "${SUBNET_PREFIX:-172.23.0}.30"
    profiles:
      - onboarding
      - operation
      - marketplace


networks:
  participant_network:
    name: sedimark-toolbox-mvm
    ipam:
      driver: default
      config:
        - subnet: "${SUBNET:-172.23.0.0/24}"


volumes:
  participant-postgres-vol:
